[package]
name = "path_tracer"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
bytemuck = "1.22.0"
glam = "0.30.0"
legion = "0.4.0"
log = "0.4.26"
simple_logger = "5.0.0"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
winit = "0.30.9"
